version: '3'

services:
### APP Service (Swoole) ##########################
  swoole_server:
    container_name: container_swoole_server
    build: ./swoole/
    ports:
      - "5000:80"
    volumes:
      - ./lumen/:/var/www
    depends_on:
      - db_server
    links:
      - "db_server:db_server"

### DB Service (MySQL) ##########################
  db_server:
    container_name: container_db_server
    build: ./mysql/
    ports:
      - "6609:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

### CACHE Service (REDIS) ##########################
  cache_server:
    container_name: container_cache_server
    build: ./redis/
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
