version: '3'

services:
  swoole:
    build: ./swoole/
    ports:
      - "5000:80"
    volumes:
      - ./lumen/:/var/www
    depends_on:
      - db_server
    links:
      - "db_server:db_server"

  db_server:
    build: ./mysql/
    ports:
      - "6609:3306"
    environment:
      - MYSQL_DATABASE=merchants
      - MYSQL_USER=merchant_admin
      - MYSQL_PASSWORD=password_123
      - MYSQL_ROOT_PASSWORD=password_admin
